export enum ServerState {
    PENDING = "PENDING",
    WAITING = "WAITING",
    SUCCESFULL = "SUCCESFULL",
    FAILURE = "FAILURE",
    SUCCESS = "SUCCESS",
    COMPLETED = "COMPLETED",
    WARNING = "WARNING",
    ERROR = "ERROR",
    ROLLING = "ROLLING",
    PROVISIONING = "PROVISIONING",
    PROVISIONED = "PROVISIONED",
}

export enum ClientState {
    PENDING = "PENDING",
    WAITING = "WAITING",
    SUCCESFULL = "SUCCESFULL",
    FAILURE = "FAILURE",
    SUCCESS = "SUCCESS",
    COMPLETED = "COMPLETED",
    WARNING = "WARNING",
    ERROR = "ERROR",
    ROLLING = "ROLLING",
    PROVISIONING = "PROVISIONING",
    PROVISIONED = "PROVISIONED",

    LOADING = "LOADING",
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS",

    TIMEDOUT = "TIMEDOUT",
}
